version: '3.8'

services:
  notification-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/notification-db
      - AWS_REGION=us-east-1
      - NOTIFICATION_QUEUE_NAME=image-pipeline-app-dev-notification-queue
      - AWS_ACCESS_KEY_ID=your_aws_access_key
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_key
      - SMTP_HOST=smtp.mailtrap.io
      - SMTP_PORT=2525
      - SMTP_USER=test
      - SMTP_PASS=test
      - WEBHOOK_RETRY_LIMIT=3
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
